# Generated by Django 4.2.11 on 2026-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detento',
            name='regime',
            field=models.CharField(choices=[('FECHADO', 'Fechado'), ('SEMIABERTO', 'Semiaberto'), ('ABERTO', 'Aberto')], default='FECHADO', max_length=15),
            preserve_default=False,
        ),
    ]
