# Generated by Django 4.2.11 on 2026-08-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentos', '0002_detento_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detento',
            name='regime',
            field=models.CharField(choices=[('FECHADO', 'Fechado'), ('SEMIABERTO', 'Semiaberto'), ('ABERTO', 'Aberto')], error_messages={'blank': 'Atenção: Insira o regime do detento!', 'required': 'Atenção: Insira o regime do detento!'}, max_length=15),
        ),
    ]
