# Generated by Django 4.2.11 on 2026-09-07 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detentos', '0003_alter_detento_regime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('ATESTADO_ESTUDO', 'Atestado de Estudo'), ('ATESTADO_TRABALHO', 'Atestado de Trabalho'), ('DOCUMENTO_PROCESSUAL', 'Documento Processual')], max_length=25)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('estado_assinatura', models.CharField(choices=[('VALIDADO', 'Assinatura Válida (ICP-Brasil)'), ('INVALIDO', 'Assinatura Inválida'), ('SEM_ASSINATURA', 'Sem Assinatura Digital')], default='SEM_ASSINATURA', max_length=15)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('detento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='detentos.detento')),
            ],
        ),
    ]
