# Generated by Django 4.2.11 on 2026-09-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentos', '0004_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detento',
            name='dias_cumpridos_informados',
            field=models.IntegerField(default=0, help_text='Dias já descontados da pena por tempo de cumprimento, conforme informado pela Vara de Execução Penal (fora do escopo de cálculo do SIR).'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
    ]
