# Generated by Django 4.2.11 on 2026-09-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentos', '0005_detento_dias_cumpridos_informados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado_assinatura',
            field=models.CharField(choices=[('VALIDADO', 'Assinatura Válida (ICP-Brasil)'), ('INVALIDO', 'Assinatura Inválida'), ('SEM_ASSINATURA', 'Sem Assinatura Digital'), ('PENDENTE', 'Assinatura Pendente')], default='PENDENTE', max_length=15),
        ),
    ]
