# Generated by Django 4.2.11 on 2026-09-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentos', '0006_alter_documento_estado_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='detento',
            name='tipo_crime',
            field=models.CharField(choices=[('COMUM', 'Crime Comum'), ('HEDIONDO_EQUIPARADO', 'Crime Hediondo ou Equiparado')], default='COMUM', help_text='Classificação conforme a Lei nº 8.072/1990, para fins de verificação de elegibilidade e frações de progressão de regime.', max_length=25),
        ),
    ]
