# Generated by Django 4.2.11 on 2026-09-11 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detentos', '0007_detento_tipo_crime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('oab', models.CharField(help_text='Número de registro na OAB (ex: 123456/SP)', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoRemicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='detentos.advogado')),
                ('detento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='detentos.detento')),
            ],
        ),
        migrations.AddField(
            model_name='detento',
            name='advogado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detentos_vinculados', to='detentos.advogado'),
        ),
    ]
